# Итерационные методы решения СЛАУ
## Метод Зейделя

In [1]:
import random
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# Невязка
def residual(A, X, F):
    return np.linalg.norm(np.dot(A,X) - F)

# Число обусловленности
def condition_num(A):
    A_inv = np.linalg.inv(A)
    
    A_norm     = np.linalg.norm(A, np.inf)
    A_inv_norm = np.linalg.norm(A_inv, np.inf)
    
    mu = A_norm * A_inv_norm
    
    return mu

In [3]:
def Seidel_method(A_copy, F_copy, X_init, eps):
    
    error = 10   # начальная погрешность 
    n = X_init.shape[0]
    
    X_prev = X_init
    iterations = 0
    
    while error >= eps:
        X = np.zeros(n).reshape((n, 1))
        
        for i in range(n):
            sum_1 = np.sum([A[i, j] * X[j, 0]      for j in range(i)])
            sum_2 = np.sum([A[i, j] * X_prev[j, 0] for j in range(i + 1, n)])
            
            X[i, 0] = ((-1) * sum_1 + (-1) * sum_2 + F[i, 0]) / A[i, i]
            
        error = max(abs((X - X_prev).flatten()))
        
        iterations += 1
        X_prev = X        
    
    return X, iterations        

In [4]:
# Решение СЛАУ
def solve_SLE(A, F, X_init, eps):
    A_copy = np.array(A)
    F_copy = np.array(F)
    
    X, iterations = Seidel_method(A_copy, F_copy, X_init, eps)
    
    return X, iterations

## Исходные данные

In [5]:
n   = 5
eps = 1.0e-15

In [6]:
# A  = np.zeros((n, n))
L_T = np.zeros((n, n))
F   = np.zeros(n).reshape((n, 1))
X_init = np.ones(n).reshape((n, 1)) 

In [7]:
for i in range(n):
    for j in range(i + 1, n):
        L_T[i, j] = random.random() * 10 * random.choice([1, -1])
    L_T[i, i] = random.random() * 10 + 1
    F[i, 0]   = random.random() * 10
    
L = np.transpose(L_T)    
A = np.dot(L, L_T)

In [8]:
print('A = ', A, end='\n\n')
print('F = ', F, end='\n\n')

A =  [[ 39.67085698 -58.87809015 -34.5075633   39.94651562 -46.85590704]
 [-58.87809015 143.25666224  38.82542082 -49.78238522  71.6633785 ]
 [-34.5075633   38.82542082  50.67588562 -70.7838156   35.10218317]
 [ 39.94651562 -49.78238522 -70.7838156  144.15046681  -3.32467006]
 [-46.85590704  71.6633785   35.10218317  -3.32467006  96.20303609]]

F =  [[0.53158502]
 [9.7502462 ]
 [9.82434931]
 [4.5743369 ]
 [8.33111006]]



## Метод Зейделя

In [9]:
try:
    X, iterations = solve_SLE(A, F, X_init, eps)
except ValueError as value_error:
    print(value_error)

In [10]:
iterations

585

In [11]:
print("Невязка: ", residual(A, X, F))

Невязка:  7.973627637051608e-14


In [12]:
print("Число обусловленности: ", condition_num(A))

Число обусловленности:  277.4347070759129


In [13]:
np.dot(A,X)

array([[0.53158502],
       [9.7502462 ],
       [9.82434931],
       [4.5743369 ],
       [8.33111006]])

In [14]:
F

array([[0.53158502],
       [9.7502462 ],
       [9.82434931],
       [4.5743369 ],
       [8.33111006]])