# Итерационные методы решения СЛАУ
## Метод Зейделя

In [1]:
import random
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# Невязка
def residual(A, X, F):
    return np.linalg.norm(np.dot(A,X) - F)

# Число обусловленности
def condition_num(A):
    A_inv = np.linalg.inv(A)
    
    A_norm = np.linalg.norm(A, np.inf)
    A_inv_norm = np.linalg.norm(A_inv, np.inf)
    
    mu = A_norm * A_inv_norm
    
    return mu

In [3]:
def Seidel_method(A_copy, F_copy, X_init, eps):
    
    error = 10   # начальная погрешность 
    n = X_init.shape[0]
    
    X = X_init    
    while error >= eps:
        
        X_prev = X
        X = np.zeros(n).reshape((n, 1))
        
        for i in range(n):
            sum_1 = sum([A[i, j] * X_prev[j, 0] / A[i, i] for j in range(i + 1, n)])
            
            if i - 1 < 0:
                X[i, 0] = (-1) * sum_1 + F[i, 0] / A[i, i]
            else:
                sum_2 = sum([A[i, j] * X[j, 0] / A[i, i] for j in range(i - 1)])
                X[i, 0] = (-1) * sum_2 - sum_1 + F[i, 0] / A[i, i]
        
        error = max(abs((X - X_prev).flatten()))
        print(error)
    
    return X        

In [4]:
# Решение СЛАУ
def solve_SLE(A, F, X_init, eps):
    A_copy = np.array(A)
    F_copy = np.array(F)
    
    # Диагональные элементы не ноль
#     permutation(A_copy, F_copy)  # перестановка строк

    X = Seidel_method(A_copy, F_copy, X_init, eps)
    
    return X

## Исходные данные

In [5]:
n   = 3
eps = 10**(-15)

In [6]:
A  = np.zeros((n, n))
F  = np.zeros(n).reshape((n, 1))
X_init = np.zeros(n).reshape((n, 1)) 

In [7]:
flag = 0

while flag != 1:
    for i in range(n):
        for j in range(i + 1, n):
            A[i, j] = random.random() * 10 * random.choice([1, -1])
            A[j, i] = A[i, j]
        
        A[i, i] = random.random() * 10 * random.choice([1, -1])
        F[i, 0] = random.random() * 10 * random.choice([1, -1])
        
        while A[i, i] == 0:
            A[i, i] = random.random() * 10 * random.choice([1, -1])
    
    w, v = np.linalg.eig(A)
    
    if all(np.logical_and(np.imag(w) == 0, w > 0)):
        print(w)
        flag = 1

[11.02015193  0.16716207  4.53716455]


In [8]:
# A = np.array([[100, 99],[99, 98]])
# F = np.array([199, 197]).reshape((2, 1)) 
# X_init = np.ones(2).reshape((2, 1))

In [9]:
print('A = ', A, end='\n\n')
print('F = ', F, end='\n\n')

A =  [[ 3.89633159 -4.53437926 -2.33488053]
 [-4.53437926  7.33172726  0.66317966]
 [-2.33488053  0.66317966  4.4964197 ]]

F =  [[-7.16019181]
 [ 9.78937943]
 [ 3.56011528]]



## Метод Зейделя

In [10]:
try:
    X = solve_SLE(A, F, X_init, eps)
except ValueError as value_error:
    print(value_error)

1.8376751673727907
1.4564820003517982
0.4703276823772089
0.06674078928533733
0.004940845513846881
0.0051856519854214245
0.001343576275305347
0.00013463161256321854
3.154824646323107e-05
1.717628654107628e-05
3.6203672697521228e-06
1.8768435672278372e-07
1.394931876674832e-07
5.36661626249213e-08
9.074678786191726e-09
4.262397101939541e-10
5.301652450384609e-10
1.589801623680387e-10
2.0491386365506514e-11
2.3141488725286763e-12
1.8398615964088094e-12
4.4630965589931293e-13
3.8191672047105385e-14
1.2434497875801753e-14
5.773159728050814e-15
1.5543122344752192e-15
2.220446049250313e-16


In [11]:
print("Невязка: ", residual(A, X, F))

Невязка:  1.0597013032056792


In [12]:
print("Число обусловленности: ", condition_num(A))

Число обусловленности:  98.15538702475425


In [13]:
np.dot(A,X)

array([[-7.16019181],
       [ 9.13496453],
       [ 4.39360672]])

In [14]:
F

array([[-7.16019181],
       [ 9.78937943],
       [ 3.56011528]])

<!-- ![image-2.png](attachment:image-2.png) -->

<!-- ![image.png](attachment:image.png) -->